project_id = "wevlxnlaxyzsobkaeoyi"

[functions.track-view]
verify_jwt = false


[functions.invite-tenant-user]
verify_jwt = false

[functions.update-tenant-user]
verify_jwt = false

[functions.hard-delete-auth-user]
verify_jwt = false
